In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [8]:
print(x)

[['Secang' 10.0 10000.0]
 ['Grabak' 11.0 15000.0]
 ['Muntilan' 12.0 20000.0]
 ['Grabak' 10.0 17000.0]
 ['Muntilan' 11.0 nan]
 ['Secang' 10.0 12000.0]
 ['Grabak' nan 18000.0]
 ['Secang' 12.0 14000.0]
 ['Muntilan' 12.0 24000.0]
 ['Secang' 10.0 13000.0]]


In [9]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [11]:
print(x)

[['Secang' 10.0 10000.0]
 ['Grabak' 11.0 15000.0]
 ['Muntilan' 12.0 20000.0]
 ['Grabak' 10.0 17000.0]
 ['Muntilan' 11.0 15888.888888888889]
 ['Secang' 10.0 12000.0]
 ['Grabak' 10.88888888888889 18000.0]
 ['Secang' 12.0 14000.0]
 ['Muntilan' 12.0 24000.0]
 ['Secang' 10.0 13000.0]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[0.0 0.0 1.0 10.0 10000.0]
 [1.0 0.0 0.0 11.0 15000.0]
 [0.0 1.0 0.0 12.0 20000.0]
 [1.0 0.0 0.0 10.0 17000.0]
 [0.0 1.0 0.0 11.0 15888.888888888889]
 [0.0 0.0 1.0 10.0 12000.0]
 [1.0 0.0 0.0 10.88888888888889 18000.0]
 [0.0 0.0 1.0 12.0 14000.0]
 [0.0 1.0 0.0 12.0 24000.0]
 [0.0 0.0 1.0 10.0 13000.0]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [17]:
print(x_train)

[[1.0 0.0 0.0 10.88888888888889 18000.0]
 [0.0 1.0 0.0 11.0 15888.888888888889]
 [0.0 0.0 1.0 10.0 10000.0]
 [1.0 0.0 0.0 10.0 17000.0]
 [1.0 0.0 0.0 11.0 15000.0]
 [0.0 0.0 1.0 12.0 14000.0]
 [0.0 1.0 0.0 12.0 24000.0]
 [0.0 0.0 1.0 10.0 12000.0]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 12.0 20000.0]
 [0.0 0.0 1.0 10.0 13000.0]]


In [19]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [20]:
print(y_test)

[0 1]


In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [22]:
print(x_train)

[[1.0 0.0 0.0 0.03564615028997697 0.5716835381378811]
 [0.0 1.0 0.0 0.1782307514498803 0.03857987067188144]
 [0.0 0.0 1.0 -1.105030658989254 -1.4484987806806435]
 [1.0 0.0 0.0 -1.105030658989254 0.31916074828556545]
 [1.0 0.0 0.0 0.1782307514498803 -0.18588483141906567]
 [0.0 0.0 1.0 1.4614921618890147 -0.4384076212713813]
 [0.0 1.0 0.0 1.4614921618890147 2.0868202772517743]
 [0.0 0.0 1.0 -1.105030658989254 -0.9434532009760124]]


In [23]:
print(x_test)

[[0.0 1.0 0.0 1.4614921618890147 1.0767291178425122]
 [0.0 0.0 1.0 -1.105030658989254 -0.6909304111236968]]
